### ISSUE TITLE
chore: set up repository pipeline with linter

### ISSUE THREAD

**Issue by amiicao** [dannyl1u/doppelganger#35]
A pipeline is an integral structure used to hold stages of development.
Add a pipeline to the repository with a linter stage to keep code consistent amongst devs and prevent errors.

TODO:
* create pipeline
* create lint stage
* use the linters black & flake8

See the following linters:
1. [black ](https://pypi.org/project/black/)
2. [flake8](https://pypi.org/project/flake8/)

**Comment by dannyl1u** [comment]
see https://pypi.org/project/pylint/

**Comment by amiicao** [comment]
Flake8 is too slow on my local machine. PyLint is supposedly even slower than Flake8. I am opting for a more modern linter: [Ruff](https://docs.astral.sh/ruff/)
